const cardImgStyle = (theme) => ({
  cardWrap: {
    width: '100%',
    position: 'relative',
    minHeight: '1px',
    paddingLeft: '15px',
    paddingRight: '15px',
  },
  cardBody: {
    color: 'rgba(0, 0, 0, 0.87)',
    width: '100%',
    border: '0',
    display: 'flex',
    position: 'relative',
    fontSize: '.875rem',
    minWidth: '0',
    wordWrap: 'break-word',
    background: '#FFF',
    boxShadow: '0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12)',
    marginTop: '50px',
    borderRadius: '6px',
    marginBottom: '30px',
    flexDirection: 'column',
    cursor: 'pointer',
  },
  cardImg: {
    padding: '0',
    zIndex: 1,
    position: 'relative',
    marginTop: '-30px',
    marginLeft: '15px',
    marginRight: '15px',
    borderRadius: '6px',
    border: 0,
    marginBottom: 0,
    height: '100%',
    '& a': {
      display: 'block',
    },
    '& img': {
      width: '100%',
      boxShadow: '0 5px 15px -8px rgba(0, 0, 0, 0.24), 0 8px 10px -5px rgba(0, 0, 0, 0.2)',
      borderRadius: 6,
      pointerEvents: 'none',
    },
  },
  cardImgBg: {
    top: 12,
    width: '100%',
    filter: 'blur(12px)',
    height: '100%',
    opacity: 1,
    zIndex: -1,
    position: 'absolute',
    transform: 'scale(0.94)',
    transition: 'opacity .45s',
    backgroundSize: 'cover',
  },
  cardTxt: {
    flex: '1 1 auto',
    padding: '0.9375rem 1.875rem',
    '-webkit-box-flex': 1,
  },
  cardTxtSubTitle: {
    fontSize: 14,
    fontFamily: '"NanumGothic", "Roboto", "Helvetica", "Arial", sans-serif',
    fontWeight: 300,
    lineHeight: '1.5em',
    color: theme.palette.primary.main,
    display: 'inline-block',
  },
  cardTxtTitle: {
    '&, & a': {
      color: '#3C4858',
      marginTop: '4px',
      minHeight: 'auto',
      fontFamily: '"NanumGothic", "Roboto Slab", "Times New Roman", serif',
      fontWeight: 700,
      marginBottom: '2px',
      textDecoration: 'none',
      fontSize: 16,
    },
  },
  cardTxtCont: {
    color: '#999',
  },
  careTxtEllipsis: {
    width: '100%',
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardTxtContNone: {
    marginBottom: 10,
  },
  txtBaronPrColor: {
    color: theme.palette.primary.main,
  },
  cardMainImg: {
    backgroundSize: 'cover',
    backgroundPositionX: 'center',
    backgroundPositionY: 'center',
    borderRadius: 6,
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '\'\'',
      width: '100%',
      height: '100%',
      position: 'absolute',
      backgroundImage: 'inherit',
      backgroundSize: 'cover',
      backgroundPositionX: 'center',
      backgroundPositionY: 'center',
      borderRadius: 6,
      transform: 'rotate(0deg)',
    },
    '&:hover': {
      '&::before': {
        content: '\'\'',
        width: '100%',
        height: '100%',
        position: 'absolute',
        backgroundImage: 'inherit',
        backgroundSize: 'cover',
        backgroundPositionX: 'center',
        backgroundPositionY: 'center',
        borderRadius: 6,
        transform: 'rotate(-6deg) scale(1.2)',
        transition: 'transform .15s',
      },
    },
  },
});

export default cardImgStyle;
